# Generated by Django 4.0 on 2021-12-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='button_url',
            field=models.URLField(default='https://www.youtube.com/'),
        ),
    ]
