# Generated by Django 4.0 on 2021-12-28 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0003_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='yt_link',
            field=models.CharField(default='https://www.youtube.com/', max_length=255),
        ),
    ]
